# Generated by Django 4.1.5 on 2023-01-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='ids',
        ),
    ]
