# Generated by Django 4.1.5 on 2023-01-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_id_user_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.ImageField(upload_to='food_recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ids',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
