# Generated by Django 4.1.5 on 2023-01-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_ingredients_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ids',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
