# Generated by Django 4.1.5 on 2023-01-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_ingredients_ingredient_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ids',
            new_name='id',
        ),
    ]
